// This file is auto-generated by @hey-api/openapi-ts

export type Body_coupons_upload_coupons_excel = {
    file: (Blob | File);
};

export type Body_coupons_upload_coupons_json = {
    file: (Blob | File);
};

export type CampaignCreate = {
    name: string;
    description?: (string | null);
    active?: boolean;
    created_at?: string;
};

export type CampaignRead = {
    name: string;
    description?: (string | null);
    active?: boolean;
    created_at?: string;
    id: number;
};

export type CampaignUpdate = {
    name?: (string | null);
    description?: (string | null);
    active?: (boolean | null);
};

export type CouponRead = {
    code: string;
    campaign_id?: (number | null);
    assigned_to_user?: (number | null);
    assigned_at?: (string | null);
    redeemed?: boolean;
    redeemed_at?: (string | null);
    metadata_?: ({
    [key: string]: unknown;
} | null);
    created_at?: string;
    updated_at?: string;
    id: number;
};

export type CouponUpdate = {
    code?: (string | null);
    campaign_id?: (number | null);
    assigned_to_user?: (number | null);
    assigned_at?: (string | null);
    redeemed?: (boolean | null);
    redeemed_at?: (string | null);
    metadata_?: ({
    [key: string]: unknown;
} | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemOut = {
    title: string;
    description?: (string | null);
    id: number;
    owner_id: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    username: string;
    roles?: Array<(string)>;
    attributes?: {
        [key: string]: unknown;
    };
    created_at?: string;
    password: string;
};

export type UserCreateOld = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    windows_username?: (string | null);
    password: string;
};

export type UserOutOld = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    windows_username?: (string | null);
    id: number;
};

export type UserRead = {
    username: string;
    roles?: Array<(string)>;
    attributes?: {
        [key: string]: unknown;
    };
    created_at?: string;
    id: number;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserUpdate = {
    username?: (string | null);
    roles?: (Array<(string)> | null);
    attributes?: ({
    [key: string]: unknown;
} | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type UserUpdateOld = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    windows_username?: (string | null);
    password?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AuthReadMeData = {
    authorization?: string;
    xWindowsUser?: (string | null);
};

export type AuthReadMeResponse = (unknown);

export type AuthReadWindowsUserResponse = (unknown);

export type CampaignsCreateCampaignData = {
    authorization?: string;
    requestBody: CampaignCreate;
};

export type CampaignsCreateCampaignResponse = (CampaignRead);

export type CampaignsReadCampaignsData = {
    authorization?: string;
    limit?: number;
    skip?: number;
};

export type CampaignsReadCampaignsResponse = (Array<CampaignRead>);

export type CampaignsReadCampaignData = {
    authorization?: string;
    id: number;
};

export type CampaignsReadCampaignResponse = (CampaignRead);

export type CampaignsUpdateCampaignData = {
    authorization?: string;
    id: number;
    requestBody: CampaignUpdate;
};

export type CampaignsUpdateCampaignResponse = (CampaignRead);

export type CampaignsDeleteCampaignData = {
    authorization?: string;
    id: number;
};

export type CampaignsDeleteCampaignResponse = (boolean);

export type CampaignsAssignCampaignToUserData = {
    authorization?: string;
    campaignId: number;
    userId: number;
};

export type CampaignsAssignCampaignToUserResponse = (CouponRead);

export type CouponsReadMyCouponsData = {
    authorization?: string;
};

export type CouponsReadMyCouponsResponse = (Array<CouponRead>);

export type CouponsReadUnassignedCouponsData = {
    authorization?: string;
};

export type CouponsReadUnassignedCouponsResponse = (Array<CouponRead>);

export type CouponsReadAvailableCouponsData = {
    authorization?: string;
};

export type CouponsReadAvailableCouponsResponse = (Array<CouponRead>);

export type CouponsReadAllCouponsData = {
    authorization?: string;
};

export type CouponsReadAllCouponsResponse = (Array<CouponRead>);

export type CouponsReadCampaignCouponsData = {
    authorization?: string;
    campaignId: number;
};

export type CouponsReadCampaignCouponsResponse = (Array<CouponRead>);

export type CouponsUploadCouponsExcelData = {
    authorization?: string;
    formData: Body_coupons_upload_coupons_excel;
};

export type CouponsUploadCouponsExcelResponse = (Array<CouponRead>);

export type CouponsUploadCouponsJsonData = {
    authorization?: string;
    formData: Body_coupons_upload_coupons_json;
};

export type CouponsUploadCouponsJsonResponse = (Array<CouponRead>);

export type CouponsAssignCouponData = {
    authorization?: string;
    couponId: number;
    userId: number;
};

export type CouponsAssignCouponResponse = (CouponRead);

export type CouponsRedeemCouponData = {
    authorization?: string;
    couponId: number;
};

export type CouponsRedeemCouponResponse = (CouponRead);

export type CouponsDeleteCouponData = {
    authorization?: string;
    id: number;
};

export type CouponsDeleteCouponResponse = (boolean);

export type CouponsUpdateCouponData = {
    authorization?: string;
    id: number;
    requestBody: CouponUpdate;
};

export type CouponsUpdateCouponResponse = (CouponRead);

export type CouponUsersReadUsersData = {
    authorization?: string;
};

export type CouponUsersReadUsersResponse = (Array<UserRead>);

export type CouponUsersCreateUserData = {
    authorization?: string;
    requestBody: UserCreate;
};

export type CouponUsersCreateUserResponse = (UserRead);

export type CouponUsersReadUserMeData = {
    authorization?: string;
};

export type CouponUsersReadUserMeResponse = (UserRead);

export type CouponUsersUpdateUserData = {
    authorization?: string;
    requestBody: UserUpdate;
    userId: number;
};

export type CouponUsersUpdateUserResponse = (UserRead);

export type CouponUsersDeleteUserData = {
    authorization?: string;
    userId: number;
};

export type CouponUsersDeleteUserResponse = (unknown);

export type ItemsReadItemsData = {
    authorization?: string;
    limit?: number;
    skip?: number;
    xWindowsUser?: (string | null);
};

export type ItemsReadItemsResponse = ({
    [key: string]: unknown;
});

export type ItemsCreateItemData = {
    authorization?: string;
    requestBody: ItemCreate;
    xWindowsUser?: (string | null);
};

export type ItemsCreateItemResponse = (ItemOut);

export type ItemsReadItemData = {
    authorization?: string;
    id: string;
    xWindowsUser?: (string | null);
};

export type ItemsReadItemResponse = (ItemOut);

export type ItemsUpdateItemData = {
    authorization?: string;
    id: string;
    requestBody: ItemUpdate;
    xWindowsUser?: (string | null);
};

export type ItemsUpdateItemResponse = (ItemOut);

export type ItemsDeleteItemData = {
    authorization?: string;
    id: string;
    xWindowsUser?: (string | null);
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginWindowResponse = (unknown);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    authorization?: string;
    email: string;
    xWindowsUser?: (string | null);
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserOutOld);

export type UsersReadUsersData = {
    authorization?: string;
    limit?: number;
    skip?: number;
    xWindowsUser?: (string | null);
};

export type UsersReadUsersResponse = (Array<UserOutOld>);

export type UsersCreateUserData = {
    authorization?: string;
    requestBody: UserCreateOld;
    xWindowsUser?: (string | null);
};

export type UsersCreateUserResponse = (UserOutOld);

export type UsersUpdateUserMeData = {
    authorization?: string;
    requestBody: UserUpdateMe;
    xWindowsUser?: (string | null);
};

export type UsersUpdateUserMeResponse = (UserOutOld);

export type UsersReadUserMeData = {
    authorization?: string;
    xWindowsUser?: (string | null);
};

export type UsersReadUserMeResponse = (UserOutOld);

export type UsersDeleteUserMeData = {
    authorization?: string;
    xWindowsUser?: (string | null);
};

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdatePasswordMeData = {
    authorization?: string;
    requestBody: UpdatePassword;
    xWindowsUser?: (string | null);
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserOutOld);

export type UsersReadUserByIdData = {
    authorization?: string;
    userId: number;
    xWindowsUser?: (string | null);
};

export type UsersReadUserByIdResponse = (UserOutOld);

export type UsersUpdateUserData = {
    authorization?: string;
    requestBody: UserUpdateOld;
    userId: number;
    xWindowsUser?: (string | null);
};

export type UsersUpdateUserResponse = (UserOutOld);

export type UsersDeleteUserData = {
    authorization?: string;
    userId: number;
    xWindowsUser?: (string | null);
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    authorization?: string;
    xWindowsUser?: (string | null);
};

export type UtilsTestEmailResponse = (Message);

export type WindowsAuthLoginWithWindowsResponse = (unknown);